language: node_js

node_js:
  - 'node'
  - '12'
  - '8'

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

branches:
  only:
    - master
    - /^release-.*/

install:
  - npm run setup

cache:
  directories:
    - node_modules

git:
  depth: 1

script:
  - npm test
